# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7fce85c6858a8d2350205d593f3f6e26a5eec397e997284f32c75b9bff1fb4291552b8cea419f0056b23430e1c1bddf8d97602d8a2ead958e2e87e907aca0de0

test:
  secret_key_base: 33b89d16851c704c4f6499730bdc9a51608889526db45667ea8af0f0c809623a1a8f0d4c8c55a5b69a7ca5901a42dd4f137b1d137c93014433526cce50fc8138

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
